/*
 * Cloudburst
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
	"strings"
)

// A TargetsApiController binds http requests to an api service and writes the service results to the http response
type TargetsApiController struct {
	service TargetsApiServicer
}

// NewTargetsApiController creates a default api controller
func NewTargetsApiController(s TargetsApiServicer) Router {
	return &TargetsApiController{ service: s }
}

// Routes returns all of the api route for the TargetsApiController
func (c *TargetsApiController) Routes() Routes {
	return Routes{ 
		{
			"ListScrapeTargets",
			strings.ToUpper("Get"),
			"/api/v1/targets",
			c.ListScrapeTargets,
		},
	}
}

// ListScrapeTargets - List ScrapeTargets
func (c *TargetsApiController) ListScrapeTargets(w http.ResponseWriter, r *http.Request) { 
	result, err := c.service.ListScrapeTargets(r.Context())
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}
