/*
 * Cloudburst
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// TargetsApiService is a service that implents the logic for the TargetsApiServicer
// This service should implement the business logic for every endpoint for the TargetsApi API. 
// Include any external packages or services that will be required by this service.
type TargetsApiService struct {
}

// NewTargetsApiService creates a default api service
func NewTargetsApiService() TargetsApiServicer {
	return &TargetsApiService{}
}

// ListScrapeTargets - List ScrapeTargets
func (s *TargetsApiService) ListScrapeTargets(ctx context.Context) (ImplResponse, error) {
	// TODO - update ListScrapeTargets with the required logic for this service method.
	// Add api_targets_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, ScrapeTarget{}) or use other options such as http.Ok ...
	//return Response(200, ScrapeTarget{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ListScrapeTargets method not implemented")
}

