/*
 * Cloudburst
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ScrapeTarget struct {

	Name string `json:"name"`

	Path string `json:"path"`

	Description string `json:"description"`

	Query string `json:"query"`

	ProviderSpec ProviderSpec `json:"providerSpec"`

	InstanceSpec InstanceSpec `json:"instanceSpec"`

	StaticSpec StaticSpec `json:"staticSpec"`
}
