/*
 * Cloudburst
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Instance struct {

	Name string `json:"name"`

	Target string `json:"target"`

	Endpoint string `json:"endpoint"`

	Active bool `json:"active"`

	Status InstanceStatus `json:"status"`
}
