/*
 * Cloudburst
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type InstanceStatus struct {

	Agent string `json:"agent"`

	Status string `json:"status"`

	Started time.Time `json:"started"`
}
