version: "3.9"

services:
  prometheus:
    image: prom/prometheus
    user: "1000:1000"
    volumes:
      - ./config:/prometheus
    command:
      - '--config.file=/prometheus/prometheus.yaml'
    ports:
      - 9090:9090
    restart: always
    networks:
      - promnet

  cloudburst-api:
    image: cbrgm/cloudburst-api:latest
    ports:
      - 6660:6660
      - 6661:6661
    restart: always
    volumes:
      - ../cloudburst.yaml:/cloudburst.yaml
    command:
      - '--ui.assets=/assets/'
      - '--bolt.path=/tmp/data'
      - '--file=/cloudburst.yaml'
      - '--polling.interval=25'
    networks:
      - promnet

  cloudburst-agent-alpha:
    image: cbrgm/cloudburst-agent:latest
    restart: always
    command:
      - '--name=agent-alpha'
      - '--provider=cloud-provider-alpha'
      - '--api.url=http://cloudburst-api:6660'
    networks:
      - promnet

  cloudburst-agent-beta:
    image: cbrgm/cloudburst-agent:latest
    restart: always
    command:
      - '--name=agent-beta'
      - '--provider=cloud-provider-beta'
      - '--api.url=http://cloudburst-api:6660'
    networks:
      - promnet

  cloudburst-agent-gamma:
    image: cbrgm/cloudburst-agent:latest
    restart: always
    command:
      - '--name=agent-gamma'
      - '--provider=cloud-provider-gamma'
      - '--api.url=http://cloudburst-api:6660'
    networks:
      - promnet

  cloudburst-proxy:
    image: cbrgm/cloudburst-proxy:latest
    ports:
      - 6670:6670
      - 6671:6671
    restart: always
    command:
      - '--internal.addr=:6671'
      - '--api.url=http://cloudburst-api:6660'
    networks:
      - promnet

  example-app:
    image: cbrgm/example-app:latest
    ports:
      - 9997:9997
    restart: always
    command:
      - '-port=9997'
    networks:
      - promnet

  example-blackhole:
    image: cbrgm/example-blackhole:latest
    ports:
      - 9998:9998
    restart: always
    command:
      - '-port=9998'
    networks:
      - promnet

networks:
  promnet:
    driver: bridge
