# prometheus global config
global:
  scrape_interval:     10s
  evaluation_interval: 10s
  # scrape_timeout is set to the global default (10s).

  external_labels:
    monitor: haw
    environment: Production
    service: Prometheus
    region: EU
    dc: eu-west-1

alerting:
  alertmanagers:

rule_files:
  - "prometheus.rules.yaml"

scrape_configs:
  # metrics_path defaults to '/metrics'
  # scheme defaults to 'http'.
  - job_name: prometheus

    scrape_interval: 5s
    scrape_timeout: 2s
    honor_labels: true

    static_configs:
      - targets: ['prometheus:9090']

  - job_name: cloudburst-api

    scrape_interval: 5s
    scrape_timeout: 2s
    honor_labels: true

    static_configs:
      - targets: ['cloudburst-api:6661']

  - job_name: example-app

    scrape_interval: 5s
    scrape_timeout: 2s
    honor_labels: true

    static_configs:
      - targets: ['example-app:8080']
