/*
 * Cloudburst
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// InstanceStatus struct for InstanceStatus
type InstanceStatus struct {
	Agent string `json:"agent"`
	Status string `json:"status"`
	Started time.Time `json:"started"`
}

// NewInstanceStatus instantiates a new InstanceStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstanceStatus(agent string, status string, started time.Time, ) *InstanceStatus {
	this := InstanceStatus{}
	this.Agent = agent
	this.Status = status
	this.Started = started
	return &this
}

// NewInstanceStatusWithDefaults instantiates a new InstanceStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstanceStatusWithDefaults() *InstanceStatus {
	this := InstanceStatus{}
	return &this
}

// GetAgent returns the Agent field value
func (o *InstanceStatus) GetAgent() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Agent
}

// GetAgentOk returns a tuple with the Agent field value
// and a boolean to check if the value has been set.
func (o *InstanceStatus) GetAgentOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Agent, true
}

// SetAgent sets field value
func (o *InstanceStatus) SetAgent(v string) {
	o.Agent = v
}

// GetStatus returns the Status field value
func (o *InstanceStatus) GetStatus() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *InstanceStatus) GetStatusOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *InstanceStatus) SetStatus(v string) {
	o.Status = v
}

// GetStarted returns the Started field value
func (o *InstanceStatus) GetStarted() time.Time {
	if o == nil  {
		var ret time.Time
		return ret
	}

	return o.Started
}

// GetStartedOk returns a tuple with the Started field value
// and a boolean to check if the value has been set.
func (o *InstanceStatus) GetStartedOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Started, true
}

// SetStarted sets field value
func (o *InstanceStatus) SetStarted(v time.Time) {
	o.Started = v
}

func (o InstanceStatus) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["agent"] = o.Agent
	}
	if true {
		toSerialize["status"] = o.Status
	}
	if true {
		toSerialize["started"] = o.Started
	}
	return json.Marshal(toSerialize)
}

type NullableInstanceStatus struct {
	value *InstanceStatus
	isSet bool
}

func (v NullableInstanceStatus) Get() *InstanceStatus {
	return v.value
}

func (v *NullableInstanceStatus) Set(val *InstanceStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableInstanceStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableInstanceStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstanceStatus(val *InstanceStatus) *NullableInstanceStatus {
	return &NullableInstanceStatus{value: val, isSet: true}
}

func (v NullableInstanceStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstanceStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


