/*
 * Cloudburst
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ScrapeTarget struct for ScrapeTarget
type ScrapeTarget struct {
	Name string `json:"name"`
	Path string `json:"path"`
	Description string `json:"description"`
	Query string `json:"query"`
	InstanceSpec InstanceSpec `json:"instanceSpec"`
	StaticSpec StaticSpec `json:"staticSpec"`
}

// NewScrapeTarget instantiates a new ScrapeTarget object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScrapeTarget(name string, path string, description string, query string, instanceSpec InstanceSpec, staticSpec StaticSpec, ) *ScrapeTarget {
	this := ScrapeTarget{}
	this.Name = name
	this.Path = path
	this.Description = description
	this.Query = query
	this.InstanceSpec = instanceSpec
	this.StaticSpec = staticSpec
	return &this
}

// NewScrapeTargetWithDefaults instantiates a new ScrapeTarget object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScrapeTargetWithDefaults() *ScrapeTarget {
	this := ScrapeTarget{}
	return &this
}

// GetName returns the Name field value
func (o *ScrapeTarget) GetName() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ScrapeTarget) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ScrapeTarget) SetName(v string) {
	o.Name = v
}

// GetPath returns the Path field value
func (o *ScrapeTarget) GetPath() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *ScrapeTarget) GetPathOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *ScrapeTarget) SetPath(v string) {
	o.Path = v
}

// GetDescription returns the Description field value
func (o *ScrapeTarget) GetDescription() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *ScrapeTarget) GetDescriptionOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *ScrapeTarget) SetDescription(v string) {
	o.Description = v
}

// GetQuery returns the Query field value
func (o *ScrapeTarget) GetQuery() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Query
}

// GetQueryOk returns a tuple with the Query field value
// and a boolean to check if the value has been set.
func (o *ScrapeTarget) GetQueryOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Query, true
}

// SetQuery sets field value
func (o *ScrapeTarget) SetQuery(v string) {
	o.Query = v
}

// GetInstanceSpec returns the InstanceSpec field value
func (o *ScrapeTarget) GetInstanceSpec() InstanceSpec {
	if o == nil  {
		var ret InstanceSpec
		return ret
	}

	return o.InstanceSpec
}

// GetInstanceSpecOk returns a tuple with the InstanceSpec field value
// and a boolean to check if the value has been set.
func (o *ScrapeTarget) GetInstanceSpecOk() (*InstanceSpec, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.InstanceSpec, true
}

// SetInstanceSpec sets field value
func (o *ScrapeTarget) SetInstanceSpec(v InstanceSpec) {
	o.InstanceSpec = v
}

// GetStaticSpec returns the StaticSpec field value
func (o *ScrapeTarget) GetStaticSpec() StaticSpec {
	if o == nil  {
		var ret StaticSpec
		return ret
	}

	return o.StaticSpec
}

// GetStaticSpecOk returns a tuple with the StaticSpec field value
// and a boolean to check if the value has been set.
func (o *ScrapeTarget) GetStaticSpecOk() (*StaticSpec, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.StaticSpec, true
}

// SetStaticSpec sets field value
func (o *ScrapeTarget) SetStaticSpec(v StaticSpec) {
	o.StaticSpec = v
}

func (o ScrapeTarget) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["path"] = o.Path
	}
	if true {
		toSerialize["description"] = o.Description
	}
	if true {
		toSerialize["query"] = o.Query
	}
	if true {
		toSerialize["instanceSpec"] = o.InstanceSpec
	}
	if true {
		toSerialize["staticSpec"] = o.StaticSpec
	}
	return json.Marshal(toSerialize)
}

type NullableScrapeTarget struct {
	value *ScrapeTarget
	isSet bool
}

func (v NullableScrapeTarget) Get() *ScrapeTarget {
	return v.value
}

func (v *NullableScrapeTarget) Set(val *ScrapeTarget) {
	v.value = val
	v.isSet = true
}

func (v NullableScrapeTarget) IsSet() bool {
	return v.isSet
}

func (v *NullableScrapeTarget) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScrapeTarget(val *ScrapeTarget) *NullableScrapeTarget {
	return &NullableScrapeTarget{value: val, isSet: true}
}

func (v NullableScrapeTarget) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScrapeTarget) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


