/*
 * Cloudburst
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ScrapeTarget struct for ScrapeTarget
type ScrapeTarget struct {
	Name *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	Query *string `json:"query,omitempty"`
	Value *float64 `json:"value,omitempty"`
	InstanceSpec *InstanceSpec `json:"instanceSpec,omitempty"`
	Instances *[]Instance `json:"instances,omitempty"`
}

// NewScrapeTarget instantiates a new ScrapeTarget object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScrapeTarget() *ScrapeTarget {
	this := ScrapeTarget{}
	return &this
}

// NewScrapeTargetWithDefaults instantiates a new ScrapeTarget object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScrapeTargetWithDefaults() *ScrapeTarget {
	this := ScrapeTarget{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ScrapeTarget) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScrapeTarget) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ScrapeTarget) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ScrapeTarget) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ScrapeTarget) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScrapeTarget) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ScrapeTarget) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ScrapeTarget) SetDescription(v string) {
	o.Description = &v
}

// GetQuery returns the Query field value if set, zero value otherwise.
func (o *ScrapeTarget) GetQuery() string {
	if o == nil || o.Query == nil {
		var ret string
		return ret
	}
	return *o.Query
}

// GetQueryOk returns a tuple with the Query field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScrapeTarget) GetQueryOk() (*string, bool) {
	if o == nil || o.Query == nil {
		return nil, false
	}
	return o.Query, true
}

// HasQuery returns a boolean if a field has been set.
func (o *ScrapeTarget) HasQuery() bool {
	if o != nil && o.Query != nil {
		return true
	}

	return false
}

// SetQuery gets a reference to the given string and assigns it to the Query field.
func (o *ScrapeTarget) SetQuery(v string) {
	o.Query = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *ScrapeTarget) GetValue() float64 {
	if o == nil || o.Value == nil {
		var ret float64
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScrapeTarget) GetValueOk() (*float64, bool) {
	if o == nil || o.Value == nil {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *ScrapeTarget) HasValue() bool {
	if o != nil && o.Value != nil {
		return true
	}

	return false
}

// SetValue gets a reference to the given float64 and assigns it to the Value field.
func (o *ScrapeTarget) SetValue(v float64) {
	o.Value = &v
}

// GetInstanceSpec returns the InstanceSpec field value if set, zero value otherwise.
func (o *ScrapeTarget) GetInstanceSpec() InstanceSpec {
	if o == nil || o.InstanceSpec == nil {
		var ret InstanceSpec
		return ret
	}
	return *o.InstanceSpec
}

// GetInstanceSpecOk returns a tuple with the InstanceSpec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScrapeTarget) GetInstanceSpecOk() (*InstanceSpec, bool) {
	if o == nil || o.InstanceSpec == nil {
		return nil, false
	}
	return o.InstanceSpec, true
}

// HasInstanceSpec returns a boolean if a field has been set.
func (o *ScrapeTarget) HasInstanceSpec() bool {
	if o != nil && o.InstanceSpec != nil {
		return true
	}

	return false
}

// SetInstanceSpec gets a reference to the given InstanceSpec and assigns it to the InstanceSpec field.
func (o *ScrapeTarget) SetInstanceSpec(v InstanceSpec) {
	o.InstanceSpec = &v
}

// GetInstances returns the Instances field value if set, zero value otherwise.
func (o *ScrapeTarget) GetInstances() []Instance {
	if o == nil || o.Instances == nil {
		var ret []Instance
		return ret
	}
	return *o.Instances
}

// GetInstancesOk returns a tuple with the Instances field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScrapeTarget) GetInstancesOk() (*[]Instance, bool) {
	if o == nil || o.Instances == nil {
		return nil, false
	}
	return o.Instances, true
}

// HasInstances returns a boolean if a field has been set.
func (o *ScrapeTarget) HasInstances() bool {
	if o != nil && o.Instances != nil {
		return true
	}

	return false
}

// SetInstances gets a reference to the given []Instance and assigns it to the Instances field.
func (o *ScrapeTarget) SetInstances(v []Instance) {
	o.Instances = &v
}

func (o ScrapeTarget) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.Query != nil {
		toSerialize["query"] = o.Query
	}
	if o.Value != nil {
		toSerialize["value"] = o.Value
	}
	if o.InstanceSpec != nil {
		toSerialize["instanceSpec"] = o.InstanceSpec
	}
	if o.Instances != nil {
		toSerialize["instances"] = o.Instances
	}
	return json.Marshal(toSerialize)
}

type NullableScrapeTarget struct {
	value *ScrapeTarget
	isSet bool
}

func (v NullableScrapeTarget) Get() *ScrapeTarget {
	return v.value
}

func (v *NullableScrapeTarget) Set(val *ScrapeTarget) {
	v.value = val
	v.isSet = true
}

func (v NullableScrapeTarget) IsSet() bool {
	return v.isSet
}

func (v *NullableScrapeTarget) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScrapeTarget(val *ScrapeTarget) *NullableScrapeTarget {
	return &NullableScrapeTarget{value: val, isSet: true}
}

func (v NullableScrapeTarget) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScrapeTarget) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


