/**
 * Cloudburst
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ContainerSpec from './ContainerSpec';

/**
 * The InstanceSpec model module.
 * @module model/InstanceSpec
 * @version 0.0.0
 */
class InstanceSpec {
    /**
     * Constructs a new <code>InstanceSpec</code>.
     * @alias module:model/InstanceSpec
     */
    constructor() { 
        
        InstanceSpec.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InstanceSpec</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InstanceSpec} obj Optional instance to populate.
     * @return {module:model/InstanceSpec} The populated <code>InstanceSpec</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InstanceSpec();

            if (data.hasOwnProperty('container')) {
                obj['container'] = ContainerSpec.constructFromObject(data['container']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/ContainerSpec} container
 */
InstanceSpec.prototype['container'] = undefined;






export default InstanceSpec;

