/**
 * Cloudburst
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InstanceStatus model module.
 * @module model/InstanceStatus
 * @version 0.0.0
 */
class InstanceStatus {
    /**
     * Constructs a new <code>InstanceStatus</code>.
     * @alias module:model/InstanceStatus
     */
    constructor() { 
        
        InstanceStatus.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InstanceStatus</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InstanceStatus} obj Optional instance to populate.
     * @return {module:model/InstanceStatus} The populated <code>InstanceStatus</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InstanceStatus();

            if (data.hasOwnProperty('agent')) {
                obj['agent'] = ApiClient.convertToType(data['agent'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('started')) {
                obj['started'] = ApiClient.convertToType(data['started'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {String} agent
 */
InstanceStatus.prototype['agent'] = undefined;

/**
 * @member {module:model/InstanceStatus.StatusEnum} status
 */
InstanceStatus.prototype['status'] = undefined;

/**
 * @member {Date} started
 */
InstanceStatus.prototype['started'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
InstanceStatus['StatusEnum'] = {

    /**
     * value: "unknown"
     * @const
     */
    "unknown": "unknown",

    /**
     * value: "pending"
     * @const
     */
    "pending": "pending",

    /**
     * value: "progress"
     * @const
     */
    "progress": "progress",

    /**
     * value: "failure"
     * @const
     */
    "failure": "failure",

    /**
     * value: "running"
     * @const
     */
    "running": "running",

    /**
     * value: "terminated"
     * @const
     */
    "terminated": "terminated"
};



export default InstanceStatus;

