/**
 * Cloudburst
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Instance from './Instance';

/**
 * The InstanceEvent model module.
 * @module model/InstanceEvent
 * @version 0.0.0
 */
class InstanceEvent {
    /**
     * Constructs a new <code>InstanceEvent</code>.
     * @alias module:model/InstanceEvent
     * @param type {module:model/InstanceEvent.TypeEnum} 
     * @param target {String} 
     * @param data {module:model/Instance} 
     */
    constructor(type, target, data) { 
        
        InstanceEvent.initialize(this, type, target, data);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type, target, data) { 
        obj['type'] = type;
        obj['target'] = target;
        obj['data'] = data;
    }

    /**
     * Constructs a <code>InstanceEvent</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InstanceEvent} obj Optional instance to populate.
     * @return {module:model/InstanceEvent} The populated <code>InstanceEvent</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InstanceEvent();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('target')) {
                obj['target'] = ApiClient.convertToType(data['target'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = Instance.constructFromObject(data['data']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/InstanceEvent.TypeEnum} type
 */
InstanceEvent.prototype['type'] = undefined;

/**
 * @member {String} target
 */
InstanceEvent.prototype['target'] = undefined;

/**
 * @member {module:model/Instance} data
 */
InstanceEvent.prototype['data'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
InstanceEvent['TypeEnum'] = {

    /**
     * value: "save"
     * @const
     */
    "save": "save",

    /**
     * value: "remove"
     * @const
     */
    "remove": "remove"
};



export default InstanceEvent;

