/**
 * Cloudburst
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProviderSpec model module.
 * @module model/ProviderSpec
 * @version 0.0.0
 */
class ProviderSpec {
    /**
     * Constructs a new <code>ProviderSpec</code>.
     * @alias module:model/ProviderSpec
     * @param weights {Object.<String, Number>} 
     */
    constructor(weights) { 
        
        ProviderSpec.initialize(this, weights);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, weights) { 
        obj['weights'] = weights;
    }

    /**
     * Constructs a <code>ProviderSpec</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProviderSpec} obj Optional instance to populate.
     * @return {module:model/ProviderSpec} The populated <code>ProviderSpec</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProviderSpec();

            if (data.hasOwnProperty('weights')) {
                obj['weights'] = ApiClient.convertToType(data['weights'], {'String': 'Number'});
            }
        }
        return obj;
    }


}

/**
 * @member {Object.<String, Number>} weights
 */
ProviderSpec.prototype['weights'] = undefined;






export default ProviderSpec;

