openapi: 3.0.1
info:
  title: Cloudburst
  version: 0.0.0
servers:
  - url: /api/v1
paths:
  /targets:
    get:
      summary: List ScrapeTargets
      operationId: ListScrapeTargets
      tags:
        - targets
      responses:
        '200':
          description: Listing successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ScrapeTargets"
  /targets/{target}/instances:
    put:
      summary: Update Instances for a ScrapeTarget
      operationId: SaveInstances
      tags:
        - instances
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Instances'
      parameters:
        - in: path
          name: target
          required: true
          schema:
            type: string
      responses:
        200:
          description: Status update successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Instances"
    get:
      summary: Get Instances for a ScrapeTarget
      operationId: GetInstances
      tags:
        - instances
      parameters:
        - in: path
          name: target
          required: true
          schema:
            type: string
      responses:
        200:
          description: Listing successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Instances"
components:
  schemas:
    ScrapeTarget:
      type: object
      required:
        - name
        - description
        - path
        - query
        - providerSpec
        - instanceSpec
        - staticSpec
      properties:
        name:
          type: string
        path:
          type: string
        description:
          type: string
        query:
          type: string
        providerSpec:
          $ref: '#/components/schemas/ProviderSpec'
        instanceSpec:
          $ref: '#/components/schemas/InstanceSpec'
        staticSpec:
          $ref: '#/components/schemas/StaticSpec'
    ProviderSpec:
      type: object
      required:
        - weights
      properties:
        weights:
          additionalProperties:
            type: number
    StaticSpec:
      type: object
      required:
        - endpoints
      properties:
        endpoints:
          $ref: '#/components/schemas/Endpoints'
    Endpoints:
      type: array
      items:
        type: string
    InstanceSpec:
      type: object
      required:
        - container
      properties:
        container:
          $ref: '#/components/schemas/ContainerSpec'
    ContainerSpec:
      type: object
      required:
        - name
        - image
      properties:
        name:
          type: string
        image:
          type: string
    ScrapeTargets:
      type: array
      items:
        $ref: '#/components/schemas/ScrapeTarget'
    Instance:
      type: object
      required:
        - name
        - endpoint
        - active
        - provider
        - container
        - status
      properties:
        name:
          type: string
        endpoint:
          type: string
        provider:
          type: string
        active:
          type: boolean
        container:
          $ref: '#/components/schemas/ContainerSpec'
        status:
          $ref: '#/components/schemas/InstanceStatus'
    InstanceStatus:
      type: object
      required:
        - agent
        - status
        - started
      properties:
        agent:
          type: string
        status:
          type: string
          enum: ['unknown', 'pending', 'progress', 'failure', 'running', 'terminated']
        started:
          type: string
          format: 'date-time'
    Instances:
      type: array
      items:
        $ref: '#/components/schemas/Instance'
    InstanceEvent:
      type: object
      required:
        - type
        - target
        - data
      properties:
        type:
          type: string
          enum: ['save', 'remove']
        target:
          type: string
        data:
          $ref: '#/components/schemas/Instances'